# -*- coding: utf-8 -*-
"""Matplotlib_amaliyot1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cRdwUC_f5kXdptKzoA-HS8nTjUd0cxq

# Data Science va Sun'iy Intellekt Praktikum

## 4-MODUL. VIZUALIZASIYA

## 1-AMALIYOT. `matplotlib`
"""

import pandas as pd
import numpy as np

"""Ushbu amaliyot uchun https://en.tutiempo.net/climate/ws-384570.html sahifasidagi Toshkent shahri o'rtacha havo harorati haqidagi ma'lumotlardan foydalanamiz.

![](https://i.imgur.com/lCIRIYm.png)

## 1-VAZIFA: Sahifadagi jadvalni pandas dataframega aylantirish va:
### - Yil (`Year`) ustunini index sifatida o'qish.
### - 1990 yildan avvalgi ma'lumotlar tashlab yuborish.
### - natijani `df` degan o'zgaruvchiga saqlash
"""

# JAVOBNI SHUYERGA YOZING
url= "https://en.tutiempo.net/climate/ws-384570.html"
tables = pd.read_html(url, index_col=0)
tables[0].tail(5)
df = tables[0][tables[0].index>1990]
df.head()

"""## 2-VAZIFA. Har bir ustun nimani anglatishi ham yuqoridagi sahifada joylashgan. Shu jadvalni ham chiqarish. Matnlarni [Google translate](https://translate.google.com) orqali tarjima qilib, uqib oling."""

# JAVOBNI SHUYERGA YOZING
tables[1]

"""## 3-VAZIFA. `df`ni tahlil qilamiz"""

df.info()

"""### **SAVOL**: Yuqoridagi natijadan qanday xulosaga kelish mumkin? DF dagi sonlar bilan ishlasak bo'ladimi?"""

# JAVOB:
# Afsuski, jadvalda mavjud bo'lmagan qiymatlar o'rniga tire (-) belgisi qo'yib ketilgan,
# shu sababdan jadval ustunlari son (int, float) emas matn (object) bo'lib qolgan.

"""## 4-VAZIFA. `df`dagi barcha `-` belgilarni `NaN` qiymat bilan almashtirish."""

# JAVOBNI SHUYERGA YOZING
df = df.replace("-", np.nan)
df

"""## 5-VAZIFA. `df` ustunlari qiymatlarini matndan o'nlik songa (`float`) o'zgartirish."""

# JAVOBNI SHUYERGA YOZING
df = df.astype(dtype=float)
df.head(10)

"""## 6-VAZIFA. `NaN` qiymatlar bilan ishlaymiz
### 6.1. Har bir ustundagi `NaN` qiymatlar soni va ularning proprosiyasini topish.
"""

# JAVOBNI SHUYERGA YOZING
nan_counts = df.isnull().sum()
print("Ustundagi NaN qiymatlar soni:\n", nan_counts)
nan_ratio = df.isnull().sum()/len(df)*100
print("\nProporsiya:\n", nan_ratio)

"""### 6.2. Eng ko'p `nan` qiymat mavjud ustunni tashlab yuborish va natijani saqlab qolish."""

# JAVOBNI SHUYERGA YOZING
df = df.drop(columns=[nan_counts.idxmax()])
df

"""### 6.3. Qolgan `NaN` qiymatlarni o'zingiz to'g'ri deb bilgan usulda to'ldiring (tashlab yubormang) va natijani saqlab qoling."""

# JAVOBNI SHUYERGA YOZING
df.fillna(method='ffill', inplace=True)
df

"""### 6.4. Yakuniy `df` ni csv faylga saqlab, kompyuterga (yoki githubga) yuklab olish"""

# JAVOBNI SHUYERGA YOZING
df.to_csv("matplotlib_cleaned_data1.csv", index=False)